/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ClaimRatchetJQJobsRequest } from '../models';
// @ts-ignore
import type { ClaimRatchetJQJobsResponse } from '../models';
// @ts-ignore
import type { ReportRatchetJQJobRequest } from '../models';
// @ts-ignore
import type { ReportRatchetJQJobResponse } from '../models';
/**
 * RatchetjqApi - axios parameter creator
 */
export const RatchetjqApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Long poll for the jobs this runner may run now. Returns as soon as any are available, otherwise blocks until the next job falls due, for at most 60 seconds. Claiming takes ownership: it advances the jobs it returns and moves their leases.
         * @summary Claim RatchetJQ jobs
         * @param {ClaimRatchetJQJobsRequest} claimRatchetJQJobsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        claimRatchetJQJobs: async (claimRatchetJQJobsRequest: ClaimRatchetJQJobsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'claimRatchetJQJobsRequest' is not null or undefined
            assertParamExists('claimRatchetJQJobs', 'claimRatchetJQJobsRequest', claimRatchetJQJobsRequest)
            const localVarPath = `/ratchetjq/jobs/claim`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(claimRatchetJQJobsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Hand back what this runner produced for a job it claimed. The outcome is recorded, an accept round is started for it, and the response comes as that round starts rather than when it decides — the verdict is the control plane’s to act on. A run that failed is not reported at all: its lease is what retries it.
         * @summary Report a RatchetJQ job outcome
         * @param {string} jobId ID of the claimed job the outcome belongs to
         * @param {ReportRatchetJQJobRequest} reportRatchetJQJobRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reportRatchetJQJob: async (jobId: string, reportRatchetJQJobRequest: ReportRatchetJQJobRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('reportRatchetJQJob', 'jobId', jobId)
            // verify required parameter 'reportRatchetJQJobRequest' is not null or undefined
            assertParamExists('reportRatchetJQJob', 'reportRatchetJQJobRequest', reportRatchetJQJobRequest)
            const localVarPath = `/ratchetjq/jobs/{jobId}/report`
                .replace('{jobId}', encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(reportRatchetJQJobRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RatchetjqApi - functional programming interface
 */
export const RatchetjqApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RatchetjqApiAxiosParamCreator(configuration)
    return {
        /**
         * Long poll for the jobs this runner may run now. Returns as soon as any are available, otherwise blocks until the next job falls due, for at most 60 seconds. Claiming takes ownership: it advances the jobs it returns and moves their leases.
         * @summary Claim RatchetJQ jobs
         * @param {ClaimRatchetJQJobsRequest} claimRatchetJQJobsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async claimRatchetJQJobs(claimRatchetJQJobsRequest: ClaimRatchetJQJobsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ClaimRatchetJQJobsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.claimRatchetJQJobs(claimRatchetJQJobsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RatchetjqApi.claimRatchetJQJobs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Hand back what this runner produced for a job it claimed. The outcome is recorded, an accept round is started for it, and the response comes as that round starts rather than when it decides — the verdict is the control plane’s to act on. A run that failed is not reported at all: its lease is what retries it.
         * @summary Report a RatchetJQ job outcome
         * @param {string} jobId ID of the claimed job the outcome belongs to
         * @param {ReportRatchetJQJobRequest} reportRatchetJQJobRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reportRatchetJQJob(jobId: string, reportRatchetJQJobRequest: ReportRatchetJQJobRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReportRatchetJQJobResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reportRatchetJQJob(jobId, reportRatchetJQJobRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RatchetjqApi.reportRatchetJQJob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RatchetjqApi - factory interface
 */
export const RatchetjqApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RatchetjqApiFp(configuration)
    return {
        /**
         * Long poll for the jobs this runner may run now. Returns as soon as any are available, otherwise blocks until the next job falls due, for at most 60 seconds. Claiming takes ownership: it advances the jobs it returns and moves their leases.
         * @summary Claim RatchetJQ jobs
         * @param {ClaimRatchetJQJobsRequest} claimRatchetJQJobsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        claimRatchetJQJobs(claimRatchetJQJobsRequest: ClaimRatchetJQJobsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ClaimRatchetJQJobsResponse> {
            return localVarFp.claimRatchetJQJobs(claimRatchetJQJobsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Hand back what this runner produced for a job it claimed. The outcome is recorded, an accept round is started for it, and the response comes as that round starts rather than when it decides — the verdict is the control plane’s to act on. A run that failed is not reported at all: its lease is what retries it.
         * @summary Report a RatchetJQ job outcome
         * @param {string} jobId ID of the claimed job the outcome belongs to
         * @param {ReportRatchetJQJobRequest} reportRatchetJQJobRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reportRatchetJQJob(jobId: string, reportRatchetJQJobRequest: ReportRatchetJQJobRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReportRatchetJQJobResponse> {
            return localVarFp.reportRatchetJQJob(jobId, reportRatchetJQJobRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RatchetjqApi - object-oriented interface
 */
export class RatchetjqApi extends BaseAPI {
    /**
     * Long poll for the jobs this runner may run now. Returns as soon as any are available, otherwise blocks until the next job falls due, for at most 60 seconds. Claiming takes ownership: it advances the jobs it returns and moves their leases.
     * @summary Claim RatchetJQ jobs
     * @param {ClaimRatchetJQJobsRequest} claimRatchetJQJobsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public claimRatchetJQJobs(claimRatchetJQJobsRequest: ClaimRatchetJQJobsRequest, options?: RawAxiosRequestConfig) {
        return RatchetjqApiFp(this.configuration).claimRatchetJQJobs(claimRatchetJQJobsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Hand back what this runner produced for a job it claimed. The outcome is recorded, an accept round is started for it, and the response comes as that round starts rather than when it decides — the verdict is the control plane’s to act on. A run that failed is not reported at all: its lease is what retries it.
     * @summary Report a RatchetJQ job outcome
     * @param {string} jobId ID of the claimed job the outcome belongs to
     * @param {ReportRatchetJQJobRequest} reportRatchetJQJobRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public reportRatchetJQJob(jobId: string, reportRatchetJQJobRequest: ReportRatchetJQJobRequest, options?: RawAxiosRequestConfig) {
        return RatchetjqApiFp(this.configuration).reportRatchetJQJob(jobId, reportRatchetJQJobRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

