/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ClaimedRatchetJQJob {
    /**
     * The ID of the job, which its outcome is reported against
     */
    'id': string;
    /**
     * The job type to run this job, matching the name the executor registers it under
     */
    'type': string;
    /**
     * The resource the job acts on
     */
    'resourceId': string;
    /**
     * The job input, shaped by the job type
     */
    'inParams'?: { [key: string]: any; };
    /**
     * When this claim on the job lapses. The executor must stop running it by then: past this moment the job is claimable again, so anything still working on it is racing whoever picked it up next.
     */
    'leaseExpiresAt': Date;
}

