/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ClaimRatchetJQJobsRequest {
    /**
     * How many jobs to hand over at most — the executor’s remaining concurrency budget. Capped by the server’s own batch size. Omitting it asks for a full batch.
     */
    'limit'?: number;
    /**
     * Set on the first claim after the runner starts. Takes back its interrupted jobs without waiting out leases granted to the process that died, and without spending a retry round on the restart.
     */
    'ignoreLeaseExpire'?: boolean;
}

