/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ReportRatchetJQJobResponse {
    /**
     * Whether the outcome was recorded. False means this executor held no running job of that id — a repeat report, or a job whose lease it had already lost.
     */
    'accepted': boolean;
}

