/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ReportRatchetJQJobRequest {
    /**
     * The business result the executor reached
     */
    'status': ReportRatchetJQJobRequestStatusEnum;
    /**
     * The job output, shaped by the job type. Omitted when the job produces nothing.
     */
    'outParams'?: { [key: string]: any; };
}

export const ReportRatchetJQJobRequestStatusEnum = {
    OK: 'ok',
    REJECTED: 'rejected',
    TIMEOUT: 'timeout',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type ReportRatchetJQJobRequestStatusEnum = typeof ReportRatchetJQJobRequestStatusEnum[keyof typeof ReportRatchetJQJobRequestStatusEnum];


