/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the ClaimRatchetJQJobsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClaimRatchetJQJobsRequest{}

// ClaimRatchetJQJobsRequest struct for ClaimRatchetJQJobsRequest
type ClaimRatchetJQJobsRequest struct {
	// How many jobs to hand over at most — the executor’s remaining concurrency budget. Capped by the server’s own batch size. Omitting it asks for a full batch.
	Limit *float32 `json:"limit,omitempty"`
	// Set on the first claim after the runner starts. Takes back its interrupted jobs without waiting out leases granted to the process that died, and without spending a retry round on the restart.
	IgnoreLeaseExpire *bool `json:"ignoreLeaseExpire,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ClaimRatchetJQJobsRequest ClaimRatchetJQJobsRequest

// NewClaimRatchetJQJobsRequest instantiates a new ClaimRatchetJQJobsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClaimRatchetJQJobsRequest() *ClaimRatchetJQJobsRequest {
	this := ClaimRatchetJQJobsRequest{}
	var ignoreLeaseExpire bool = false
	this.IgnoreLeaseExpire = &ignoreLeaseExpire
	return &this
}

// NewClaimRatchetJQJobsRequestWithDefaults instantiates a new ClaimRatchetJQJobsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClaimRatchetJQJobsRequestWithDefaults() *ClaimRatchetJQJobsRequest {
	this := ClaimRatchetJQJobsRequest{}
	var ignoreLeaseExpire bool = false
	this.IgnoreLeaseExpire = &ignoreLeaseExpire
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *ClaimRatchetJQJobsRequest) GetLimit() float32 {
	if o == nil || IsNil(o.Limit) {
		var ret float32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClaimRatchetJQJobsRequest) GetLimitOk() (*float32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *ClaimRatchetJQJobsRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given float32 and assigns it to the Limit field.
func (o *ClaimRatchetJQJobsRequest) SetLimit(v float32) {
	o.Limit = &v
}

// GetIgnoreLeaseExpire returns the IgnoreLeaseExpire field value if set, zero value otherwise.
func (o *ClaimRatchetJQJobsRequest) GetIgnoreLeaseExpire() bool {
	if o == nil || IsNil(o.IgnoreLeaseExpire) {
		var ret bool
		return ret
	}
	return *o.IgnoreLeaseExpire
}

// GetIgnoreLeaseExpireOk returns a tuple with the IgnoreLeaseExpire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClaimRatchetJQJobsRequest) GetIgnoreLeaseExpireOk() (*bool, bool) {
	if o == nil || IsNil(o.IgnoreLeaseExpire) {
		return nil, false
	}
	return o.IgnoreLeaseExpire, true
}

// HasIgnoreLeaseExpire returns a boolean if a field has been set.
func (o *ClaimRatchetJQJobsRequest) HasIgnoreLeaseExpire() bool {
	if o != nil && !IsNil(o.IgnoreLeaseExpire) {
		return true
	}

	return false
}

// SetIgnoreLeaseExpire gets a reference to the given bool and assigns it to the IgnoreLeaseExpire field.
func (o *ClaimRatchetJQJobsRequest) SetIgnoreLeaseExpire(v bool) {
	o.IgnoreLeaseExpire = &v
}

func (o ClaimRatchetJQJobsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClaimRatchetJQJobsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.IgnoreLeaseExpire) {
		toSerialize["ignoreLeaseExpire"] = o.IgnoreLeaseExpire
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClaimRatchetJQJobsRequest) UnmarshalJSON(data []byte) (err error) {
	varClaimRatchetJQJobsRequest := _ClaimRatchetJQJobsRequest{}

	err = json.Unmarshal(data, &varClaimRatchetJQJobsRequest)

	if err != nil {
		return err
	}

	*o = ClaimRatchetJQJobsRequest(varClaimRatchetJQJobsRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "limit")
		delete(additionalProperties, "ignoreLeaseExpire")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClaimRatchetJQJobsRequest struct {
	value *ClaimRatchetJQJobsRequest
	isSet bool
}

func (v NullableClaimRatchetJQJobsRequest) Get() *ClaimRatchetJQJobsRequest {
	return v.value
}

func (v *NullableClaimRatchetJQJobsRequest) Set(val *ClaimRatchetJQJobsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableClaimRatchetJQJobsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableClaimRatchetJQJobsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClaimRatchetJQJobsRequest(val *ClaimRatchetJQJobsRequest) *NullableClaimRatchetJQJobsRequest {
	return &NullableClaimRatchetJQJobsRequest{value: val, isSet: true}
}

func (v NullableClaimRatchetJQJobsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClaimRatchetJQJobsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


