/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the ReportRatchetJQJobRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReportRatchetJQJobRequest{}

// ReportRatchetJQJobRequest struct for ReportRatchetJQJobRequest
type ReportRatchetJQJobRequest struct {
	// The business result the executor reached
	Status string `json:"status"`
	// The job output, shaped by the job type. Omitted when the job produces nothing.
	OutParams map[string]interface{} `json:"outParams,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ReportRatchetJQJobRequest ReportRatchetJQJobRequest

// NewReportRatchetJQJobRequest instantiates a new ReportRatchetJQJobRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReportRatchetJQJobRequest(status string) *ReportRatchetJQJobRequest {
	this := ReportRatchetJQJobRequest{}
	this.Status = status
	return &this
}

// NewReportRatchetJQJobRequestWithDefaults instantiates a new ReportRatchetJQJobRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReportRatchetJQJobRequestWithDefaults() *ReportRatchetJQJobRequest {
	this := ReportRatchetJQJobRequest{}
	return &this
}

// GetStatus returns the Status field value
func (o *ReportRatchetJQJobRequest) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ReportRatchetJQJobRequest) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ReportRatchetJQJobRequest) SetStatus(v string) {
	o.Status = v
}

// GetOutParams returns the OutParams field value if set, zero value otherwise.
func (o *ReportRatchetJQJobRequest) GetOutParams() map[string]interface{} {
	if o == nil || IsNil(o.OutParams) {
		var ret map[string]interface{}
		return ret
	}
	return o.OutParams
}

// GetOutParamsOk returns a tuple with the OutParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportRatchetJQJobRequest) GetOutParamsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.OutParams) {
		return map[string]interface{}{}, false
	}
	return o.OutParams, true
}

// HasOutParams returns a boolean if a field has been set.
func (o *ReportRatchetJQJobRequest) HasOutParams() bool {
	if o != nil && !IsNil(o.OutParams) {
		return true
	}

	return false
}

// SetOutParams gets a reference to the given map[string]interface{} and assigns it to the OutParams field.
func (o *ReportRatchetJQJobRequest) SetOutParams(v map[string]interface{}) {
	o.OutParams = v
}

func (o ReportRatchetJQJobRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReportRatchetJQJobRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if !IsNil(o.OutParams) {
		toSerialize["outParams"] = o.OutParams
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReportRatchetJQJobRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReportRatchetJQJobRequest := _ReportRatchetJQJobRequest{}

	err = json.Unmarshal(data, &varReportRatchetJQJobRequest)

	if err != nil {
		return err
	}

	*o = ReportRatchetJQJobRequest(varReportRatchetJQJobRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "status")
		delete(additionalProperties, "outParams")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReportRatchetJQJobRequest struct {
	value *ReportRatchetJQJobRequest
	isSet bool
}

func (v NullableReportRatchetJQJobRequest) Get() *ReportRatchetJQJobRequest {
	return v.value
}

func (v *NullableReportRatchetJQJobRequest) Set(val *ReportRatchetJQJobRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableReportRatchetJQJobRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableReportRatchetJQJobRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportRatchetJQJobRequest(val *ReportRatchetJQJobRequest) *NullableReportRatchetJQJobRequest {
	return &NullableReportRatchetJQJobRequest{value: val, isSet: true}
}

func (v NullableReportRatchetJQJobRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportRatchetJQJobRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


