/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the ClaimedRatchetJQJob type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClaimedRatchetJQJob{}

// ClaimedRatchetJQJob struct for ClaimedRatchetJQJob
type ClaimedRatchetJQJob struct {
	// The ID of the job, which its outcome is reported against
	Id string `json:"id"`
	// The job type to run this job, matching the name the executor registers it under
	Type string `json:"type"`
	// The resource the job acts on
	ResourceId string `json:"resourceId"`
	// The job input, shaped by the job type
	InParams map[string]interface{} `json:"inParams,omitempty"`
	// When this claim on the job lapses. The executor must stop running it by then: past this moment the job is claimable again, so anything still working on it is racing whoever picked it up next.
	LeaseExpiresAt time.Time `json:"leaseExpiresAt"`
	AdditionalProperties map[string]interface{}
}

type _ClaimedRatchetJQJob ClaimedRatchetJQJob

// NewClaimedRatchetJQJob instantiates a new ClaimedRatchetJQJob object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClaimedRatchetJQJob(id string, type_ string, resourceId string, leaseExpiresAt time.Time) *ClaimedRatchetJQJob {
	this := ClaimedRatchetJQJob{}
	this.Id = id
	this.Type = type_
	this.ResourceId = resourceId
	this.LeaseExpiresAt = leaseExpiresAt
	return &this
}

// NewClaimedRatchetJQJobWithDefaults instantiates a new ClaimedRatchetJQJob object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClaimedRatchetJQJobWithDefaults() *ClaimedRatchetJQJob {
	this := ClaimedRatchetJQJob{}
	return &this
}

// GetId returns the Id field value
func (o *ClaimedRatchetJQJob) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ClaimedRatchetJQJob) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ClaimedRatchetJQJob) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *ClaimedRatchetJQJob) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ClaimedRatchetJQJob) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ClaimedRatchetJQJob) SetType(v string) {
	o.Type = v
}

// GetResourceId returns the ResourceId field value
func (o *ClaimedRatchetJQJob) GetResourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value
// and a boolean to check if the value has been set.
func (o *ClaimedRatchetJQJob) GetResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceId, true
}

// SetResourceId sets field value
func (o *ClaimedRatchetJQJob) SetResourceId(v string) {
	o.ResourceId = v
}

// GetInParams returns the InParams field value if set, zero value otherwise.
func (o *ClaimedRatchetJQJob) GetInParams() map[string]interface{} {
	if o == nil || IsNil(o.InParams) {
		var ret map[string]interface{}
		return ret
	}
	return o.InParams
}

// GetInParamsOk returns a tuple with the InParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClaimedRatchetJQJob) GetInParamsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.InParams) {
		return map[string]interface{}{}, false
	}
	return o.InParams, true
}

// HasInParams returns a boolean if a field has been set.
func (o *ClaimedRatchetJQJob) HasInParams() bool {
	if o != nil && !IsNil(o.InParams) {
		return true
	}

	return false
}

// SetInParams gets a reference to the given map[string]interface{} and assigns it to the InParams field.
func (o *ClaimedRatchetJQJob) SetInParams(v map[string]interface{}) {
	o.InParams = v
}

// GetLeaseExpiresAt returns the LeaseExpiresAt field value
func (o *ClaimedRatchetJQJob) GetLeaseExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LeaseExpiresAt
}

// GetLeaseExpiresAtOk returns a tuple with the LeaseExpiresAt field value
// and a boolean to check if the value has been set.
func (o *ClaimedRatchetJQJob) GetLeaseExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LeaseExpiresAt, true
}

// SetLeaseExpiresAt sets field value
func (o *ClaimedRatchetJQJob) SetLeaseExpiresAt(v time.Time) {
	o.LeaseExpiresAt = v
}

func (o ClaimedRatchetJQJob) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClaimedRatchetJQJob) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["resourceId"] = o.ResourceId
	if !IsNil(o.InParams) {
		toSerialize["inParams"] = o.InParams
	}
	toSerialize["leaseExpiresAt"] = o.LeaseExpiresAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClaimedRatchetJQJob) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"resourceId",
		"leaseExpiresAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClaimedRatchetJQJob := _ClaimedRatchetJQJob{}

	err = json.Unmarshal(data, &varClaimedRatchetJQJob)

	if err != nil {
		return err
	}

	*o = ClaimedRatchetJQJob(varClaimedRatchetJQJob)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "type")
		delete(additionalProperties, "resourceId")
		delete(additionalProperties, "inParams")
		delete(additionalProperties, "leaseExpiresAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClaimedRatchetJQJob struct {
	value *ClaimedRatchetJQJob
	isSet bool
}

func (v NullableClaimedRatchetJQJob) Get() *ClaimedRatchetJQJob {
	return v.value
}

func (v *NullableClaimedRatchetJQJob) Set(val *ClaimedRatchetJQJob) {
	v.value = val
	v.isSet = true
}

func (v NullableClaimedRatchetJQJob) IsSet() bool {
	return v.isSet
}

func (v *NullableClaimedRatchetJQJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClaimedRatchetJQJob(val *ClaimedRatchetJQJob) *NullableClaimedRatchetJQJob {
	return &NullableClaimedRatchetJQJob{value: val, isSet: true}
}

func (v NullableClaimedRatchetJQJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClaimedRatchetJQJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


