/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the ClaimRatchetJQJobsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClaimRatchetJQJobsResponse{}

// ClaimRatchetJQJobsResponse struct for ClaimRatchetJQJobsResponse
type ClaimRatchetJQJobsResponse struct {
	// The jobs this executor may run now
	Jobs []ClaimedRatchetJQJob `json:"jobs"`
	AdditionalProperties map[string]interface{}
}

type _ClaimRatchetJQJobsResponse ClaimRatchetJQJobsResponse

// NewClaimRatchetJQJobsResponse instantiates a new ClaimRatchetJQJobsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClaimRatchetJQJobsResponse(jobs []ClaimedRatchetJQJob) *ClaimRatchetJQJobsResponse {
	this := ClaimRatchetJQJobsResponse{}
	this.Jobs = jobs
	return &this
}

// NewClaimRatchetJQJobsResponseWithDefaults instantiates a new ClaimRatchetJQJobsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClaimRatchetJQJobsResponseWithDefaults() *ClaimRatchetJQJobsResponse {
	this := ClaimRatchetJQJobsResponse{}
	return &this
}

// GetJobs returns the Jobs field value
func (o *ClaimRatchetJQJobsResponse) GetJobs() []ClaimedRatchetJQJob {
	if o == nil {
		var ret []ClaimedRatchetJQJob
		return ret
	}

	return o.Jobs
}

// GetJobsOk returns a tuple with the Jobs field value
// and a boolean to check if the value has been set.
func (o *ClaimRatchetJQJobsResponse) GetJobsOk() ([]ClaimedRatchetJQJob, bool) {
	if o == nil {
		return nil, false
	}
	return o.Jobs, true
}

// SetJobs sets field value
func (o *ClaimRatchetJQJobsResponse) SetJobs(v []ClaimedRatchetJQJob) {
	o.Jobs = v
}

func (o ClaimRatchetJQJobsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClaimRatchetJQJobsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobs"] = o.Jobs

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClaimRatchetJQJobsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClaimRatchetJQJobsResponse := _ClaimRatchetJQJobsResponse{}

	err = json.Unmarshal(data, &varClaimRatchetJQJobsResponse)

	if err != nil {
		return err
	}

	*o = ClaimRatchetJQJobsResponse(varClaimRatchetJQJobsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "jobs")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClaimRatchetJQJobsResponse struct {
	value *ClaimRatchetJQJobsResponse
	isSet bool
}

func (v NullableClaimRatchetJQJobsResponse) Get() *ClaimRatchetJQJobsResponse {
	return v.value
}

func (v *NullableClaimRatchetJQJobsResponse) Set(val *ClaimRatchetJQJobsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClaimRatchetJQJobsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClaimRatchetJQJobsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClaimRatchetJQJobsResponse(val *ClaimRatchetJQJobsResponse) *NullableClaimRatchetJQJobsResponse {
	return &NullableClaimRatchetJQJobsResponse{value: val, isSet: true}
}

func (v NullableClaimRatchetJQJobsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClaimRatchetJQJobsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


