/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the ReportRatchetJQJobResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReportRatchetJQJobResponse{}

// ReportRatchetJQJobResponse struct for ReportRatchetJQJobResponse
type ReportRatchetJQJobResponse struct {
	// Whether the outcome was recorded. False means this executor held no running job of that id — a repeat report, or a job whose lease it had already lost.
	Accepted bool `json:"accepted"`
	AdditionalProperties map[string]interface{}
}

type _ReportRatchetJQJobResponse ReportRatchetJQJobResponse

// NewReportRatchetJQJobResponse instantiates a new ReportRatchetJQJobResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReportRatchetJQJobResponse(accepted bool) *ReportRatchetJQJobResponse {
	this := ReportRatchetJQJobResponse{}
	this.Accepted = accepted
	return &this
}

// NewReportRatchetJQJobResponseWithDefaults instantiates a new ReportRatchetJQJobResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReportRatchetJQJobResponseWithDefaults() *ReportRatchetJQJobResponse {
	this := ReportRatchetJQJobResponse{}
	return &this
}

// GetAccepted returns the Accepted field value
func (o *ReportRatchetJQJobResponse) GetAccepted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Accepted
}

// GetAcceptedOk returns a tuple with the Accepted field value
// and a boolean to check if the value has been set.
func (o *ReportRatchetJQJobResponse) GetAcceptedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Accepted, true
}

// SetAccepted sets field value
func (o *ReportRatchetJQJobResponse) SetAccepted(v bool) {
	o.Accepted = v
}

func (o ReportRatchetJQJobResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReportRatchetJQJobResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accepted"] = o.Accepted

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReportRatchetJQJobResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accepted",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReportRatchetJQJobResponse := _ReportRatchetJQJobResponse{}

	err = json.Unmarshal(data, &varReportRatchetJQJobResponse)

	if err != nil {
		return err
	}

	*o = ReportRatchetJQJobResponse(varReportRatchetJQJobResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "accepted")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReportRatchetJQJobResponse struct {
	value *ReportRatchetJQJobResponse
	isSet bool
}

func (v NullableReportRatchetJQJobResponse) Get() *ReportRatchetJQJobResponse {
	return v.value
}

func (v *NullableReportRatchetJQJobResponse) Set(val *ReportRatchetJQJobResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReportRatchetJQJobResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReportRatchetJQJobResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportRatchetJQJobResponse(val *ReportRatchetJQJobResponse) *NullableReportRatchetJQJobResponse {
	return &NullableReportRatchetJQJobResponse{value: val, isSet: true}
}

func (v NullableReportRatchetJQJobResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportRatchetJQJobResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


